[versions]

compileSdk = "33"
minSdk = "21"

kotlin-lang = "1.8.10"
androidGradlePlugin = "7.3.1"
mavenPublish = "0.24.0"

kotlin-serialization = "1.4.1"
compose-compiler = "1.4.2"
compose-main = "1.3.1"
compose-navigation = "2.5.3"

[libraries]

kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin-lang" }
kotlin-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlin-serialization" }
# compiler dependency is defined to help Renovabot update the version
compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "compose-compiler" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose-main" }
compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "compose-navigation" }
junit = { module = "junit:junit", version = "4.13.2" }
roboletric = { module = "org.robolectric:robolectric", version = "4.9.2" }

[bundles]

[plugins]
agp-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
agp-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-lang" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin-lang" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin-lang" }
mavenPublish = { id = "com.vanniktech.maven.publish.base", version.ref = "mavenPublish" }
kotlinter = { id = "org.jmailen.kotlinter", version = "3.13.0" }
